#The simplest way to work with migrations is through RAKE Tasks that we are given through a new gem, the 
#Sinatra-active record gem.  This gem provide some common Rake tasks for working with Active Record.

require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end
